# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('python3_compatible', models.NullBooleanField()),
                ('total_downloads', models.IntegerField()),
                ('description_length', models.IntegerField()),
                ('number_of_releases', models.IntegerField()),
                ('last_release_date', models.DateField()),
                ('last_release_size', models.IntegerField()),
            ],
        ),
    ]
