# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinfo',
            name='description_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='last_release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='last_release_size',
            field=models.IntegerField(null=True),
        ),
    ]
