# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_info', '0002_auto_20161219_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageinfo',
            name='development_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
