# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_info', '0005_auto_20161220_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageinfo',
            name='quality_factor',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
