# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_info', '0006_packageinfo_quality_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageinfo',
            name='first_release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='quality_factor',
            field=models.FloatField(null=True),
        ),
    ]
