# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_info', '0008_auto_20161222_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageinfo',
            name='first_release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='packageinfo',
            name='python2_classifier_present',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
